CREATE TABLE clients (
  id   INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(320) NOT NULL UNIQUE,
  plan_id INT REFERENCES plans(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE authkeys (
  client_id INT REFERENCES clients(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  access VARCHAR(10) NOT NULL UNIQUE,
  secret VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE images (
  id   INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  path VARCHAR(1087) NOT NULL UNIQUE,
  size VARCHAR(10) NOT NULL,
  type VARCHAR(7) NOT NULL,
  extension VARCHAR(3) NOT NULL,
  client_id INT REFERENCES clients(id)
);

CREATE TABLE matches (
  image1_id INT NOT NULL,
  image2_id INT NOT NULL,
  score INT NOT NULL,
  client_id INT REFERENCES clients(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);